# pylint: disable=invalid-name,no-member
"""add_multiplier_field

Revision ID: bc5b60468e3b
Revises: ff2ce0fad2ca
Create Date: 2026-02-07 13:38:46.792829

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc5b60468e3b"
down_revision: Union[str, Sequence[str], None] = "ff2ce0fad2ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devlogs",
        sa.Column("cards_per_hour", sa.Integer(), nullable=False, server_default="8"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devlogs", "cards_per_hour")
    # ### end Alembic commands ###
